#!/bin/bash

set -euo pipefail

if [ ! -e /etc/ssh/ssh_host_rsa_key ]; then
	dpkg-reconfigure openssh-server
	killall sshd
fi

cd /home
for u in *; do
	S="/bin/bash"
	[ -e "$u/.zshrc" -a -n "$(which zsh)" ] && S=$(which zsh)
	groupadd --gid "$(stat --format %g "$u")" "$u" || continue
	useradd	--uid "$(stat --format %u "$u")" \
			--gid "$(stat --format %g "$u")" \
			--groups sudo \
			--shell "$S" "$u"
done

while pgrep sshd; do
	ps faux
	echo "Waiting..."
	sleep 1
done

[ -d /var/run/sshd ] || mkdir /var/run/sshd

exec /usr/sbin/sshd -D
